CREATE TABLE IF NOT EXISTS Event_Location (
	lid INTEGER,
	mode VARCHAR(200),
	location VARCHAR(200),
	room_number INTEGER,
    virtual_link VARCHAR(200),
	PRIMARY KEY(lid)
);

CREATE TABLE IF NOT EXISTS Club_Event (
	eid INTEGER,
	lid INTEGER NOT NULL,
	flyer_url VARCHAR(200),
	description VARCHAR(200),
	start_time DATETIME,
	end_time DATETIME,
	event_name VARCHAR(300),
	PRIMARY KEY(eid),
	FOREIGN KEY(lid) REFERENCES Event_Location(lid)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS Club_EventTags (
	tid INTEGER,
	tag_name VARCHAR(200),
	PRIMARY KEY(tid)
);

CREATE TABLE IF NOT EXISTS Club_Event_to_Club_EventTags(
	eid INTEGER NOT NULL,
	tid INTEGER NOT NULL,
	PRIMARY KEY(eid, tid),
	FOREIGN KEY(eid) REFERENCES Club_Event(eid)
		ON DELETE CASCADE
		ON UPDATE NO ACTION,
	FOREIGN KEY(tid) REFERENCES Club_EventTags(tid)
		ON DELETE CASCADE
		ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS Category (
	cat_id INTEGER,
	cat_name VARCHAR(200),
	PRIMARY KEY(cat_id)
);

CREATE TABLE IF NOT EXISTS Club (
	cid INTEGER,
	club_name VARCHAR(200), 
	description VARCHAR(500),
            image VARCHAR(500),
	PRIMARY KEY(cid)
);

CREATE TABLE IF NOT EXISTS Club_to_Category (
	cat_id INTEGER NOT NULL,
	cid INTEGER NOT NULL,
	PRIMARY KEY(cat_id, cid),
	FOREIGN KEY(cat_id) REFERENCES Category(cat_id)
		ON DELETE CASCADE
		ON UPDATE NO ACTION,
	FOREIGN KEY(cid) REFERENCES Club(cid)
		ON DELETE CASCADE
		ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS Club_to_ClubEvent (
	cid INTEGER NOT NULL,
	eid INTEGER NOT NULL,
	PRIMARY KEY(cid, eid),
	FOREIGN KEY(cid) REFERENCES Club(cid)
		ON DELETE CASCADE
		ON UPDATE NO ACTION,
	FOREIGN KEY(eid) REFERENCES Club_Event(eid)
		ON DELETE CASCADE
		ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS Socials (
	platform VARCHAR(200),
	cid INTEGER NOT NULL,
	link VARCHAR(200),
	PRIMARY KEY(platform, cid),
	FOREIGN KEY(cid) REFERENCES Club(cid)
		ON DELETE CASCADE
		ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS User(
	uid INTEGER,
	full_name VARCHAR(200),
	college_year INTEGER,
	email VARCHAR(200) UNIQUE,
	username VARCHAR(200) UNIQUE,
	password VARCHAR(200),
	is_Club_Officer BOOLEAN,
	is_Admin BOOLEAN,
	PRIMARY KEY(uid)
);

CREATE TABLE IF NOT EXISTS Favorite (
	cid INTEGER NOT NULL,
	uid INTEGER NOT NULL,
	PRIMARY KEY(cid, uid),
	FOREIGN KEY(cid) REFERENCES Club(cid)
		ON DELETE CASCADE
		ON UPDATE NO ACTION,
	FOREIGN KEY(uid) REFERENCES User(uid)
		ON DELETE CASCADE
		ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS Club_to_Club_Officer(
	uid INTEGER NOT NULL,
	cid INTEGER NOT NULL,
	PRIMARY KEY(uid, cid),
	FOREIGN KEY(uid) REFERENCES User(uid)
		ON DELETE CASCADE
		ON UPDATE NO ACTION,
	FOREIGN KEY(cid) REFERENCES Club(cid)
		ON DELETE CASCADE
		ON UPDATE NO ACTION
);